const { db } = require('../sequelize')

module.exports = async () => {
    const contracts = [
        { id: '1', group_id: 1, pupil_id: 1 },
        { id: '2', group_id: 1, pupil_id: 2 },
        { id: '3', group_id: 1, pupil_id: 3 },
        { id: '4', group_id: 1, pupil_id: 4 },
        { id: '5', group_id: 1, pupil_id: 5 },
        { id: '6', group_id: 1, pupil_id: 6 },
        { id: '7', group_id: 1, pupil_id: 7 },
        { id: '8', group_id: 1, pupil_id: 8 },
        { id: '9', group_id: 1, pupil_id: 9 },
        { id: '10', group_id: 1, pupil_id: 10 },

        { id: '11', group_id: 2, pupil_id: 1 },
        { id: '12', group_id: 2, pupil_id: 2 },
        { id: '13', group_id: 2, pupil_id: 3 },
        { id: '14', group_id: 2, pupil_id: 4 },
        { id: '15', group_id: 2, pupil_id: 5 },
        { id: '16', group_id: 2, pupil_id: 6 },
        { id: '17', group_id: 2, pupil_id: 7 },
        { id: '18', group_id: 2, pupil_id: 8 },
        { id: '19', group_id: 2, pupil_id: 9 },
        { id: '20', group_id: 2, pupil_id: 10 },

        { id: '21', group_id: 3, pupil_id: 1 },
        { id: '22', group_id: 3, pupil_id: 2 },
        { id: '23', group_id: 3, pupil_id: 3 },
        { id: '24', group_id: 3, pupil_id: 4 },
        { id: '25', group_id: 3, pupil_id: 5 },
        { id: '26', group_id: 3, pupil_id: 6 },
        { id: '27', group_id: 3, pupil_id: 7 },
        { id: '28', group_id: 3, pupil_id: 8 },
        { id: '29', group_id: 3, pupil_id: 9 },
        { id: '30', group_id: 3, pupil_id: 10 },

        { id: '31', group_id: 4, pupil_id: 1 },
        { id: '32', group_id: 4, pupil_id: 2 },
        { id: '33', group_id: 4, pupil_id: 3 },
        { id: '34', group_id: 4, pupil_id: 4 },
        { id: '35', group_id: 4, pupil_id: 5 },
        { id: '36', group_id: 4, pupil_id: 6 },
        { id: '37', group_id: 4, pupil_id: 7 },
        { id: '38', group_id: 4, pupil_id: 8 },
        { id: '39', group_id: 4, pupil_id: 9 },
        { id: '40', group_id: 4, pupil_id: 10 },

        { id: '41', group_id: 5, pupil_id: 1 },
        { id: '42', group_id: 5, pupil_id: 2 },
        { id: '43', group_id: 5, pupil_id: 3 },
        { id: '44', group_id: 5, pupil_id: 4 },
        { id: '45', group_id: 5, pupil_id: 5 },
        { id: '46', group_id: 5, pupil_id: 6 },
        { id: '47', group_id: 5, pupil_id: 7 },
        { id: '48', group_id: 5, pupil_id: 8 },
        { id: '49', group_id: 5, pupil_id: 9 },
        { id: '50', group_id: 5, pupil_id: 10 },

        { id: '51', group_id: 6, pupil_id: 1 },
        { id: '52', group_id: 6, pupil_id: 2 },
        { id: '53', group_id: 6, pupil_id: 3 },
        { id: '54', group_id: 6, pupil_id: 4 },
        { id: '55', group_id: 6, pupil_id: 5 },
        { id: '56', group_id: 6, pupil_id: 6 },
        { id: '57', group_id: 6, pupil_id: 7 },
        { id: '58', group_id: 6, pupil_id: 8 },
        { id: '59', group_id: 6, pupil_id: 9 },
        { id: '60', group_id: 6, pupil_id: 10 },

        { id: '61', group_id: 7, pupil_id: 1 },
        { id: '62', group_id: 7, pupil_id: 2 },
        { id: '63', group_id: 7, pupil_id: 3 },
        { id: '64', group_id: 7, pupil_id: 4 },
        { id: '65', group_id: 7, pupil_id: 5 },
        { id: '66', group_id: 7, pupil_id: 6 },
        { id: '67', group_id: 7, pupil_id: 7 },
        { id: '68', group_id: 7, pupil_id: 8 },
        { id: '69', group_id: 7, pupil_id: 9 },
        { id: '70', group_id: 7, pupil_id: 10 },

        { id: '71', group_id: 8, pupil_id: 1 },
        { id: '72', group_id: 8, pupil_id: 2 },
        { id: '73', group_id: 8, pupil_id: 3 },
        { id: '74', group_id: 8, pupil_id: 4 },
        { id: '75', group_id: 8, pupil_id: 5 },
        { id: '76', group_id: 8, pupil_id: 6 },
        { id: '77', group_id: 8, pupil_id: 7 },
        { id: '78', group_id: 8, pupil_id: 8 },
        { id: '79', group_id: 8, pupil_id: 9 },
        { id: '80', group_id: 8, pupil_id: 10 },
    ]
    for (const contract of contracts) {
        await db.Contracts.create({ ...contract })
    }
};