const createMonths = require('./migrations/months')
const createRoles = require('./migrations/roles')
const createPupils = require('./migrations/pupils')
const createTeachers = require('./migrations/teachers')
const createCourses = require('./migrations/courses')
const createGroups = require('./migrations/groups')
const createWeekDays = require('./migrations/week-days')
const createGroupDays = require('./migrations/group-days')
const createGroupsTeachers = require('./migrations/group-teacher')
const createAttendances = require('./migrations/attendances')
const createGroupsPupils = require('./migrations/group-pupil')
const createAttendancesPupils = require('./migrations/attendances-pupils')
const createContracts = require('./migrations/contracts')
const createPayrols = require('./migrations/payrolls')
const createPupilMails = require('./migrations/pupil-mails')
const createPupilParents = require('./migrations/pupil-parents')

module.exports = async () => {
    await createMonths()
    await createRoles()
    await createPupils()
    await createTeachers()
    await createCourses()
    await createGroups()
    await createWeekDays()
    await createGroupDays()
    await createGroupsTeachers()
    await createAttendances()
    await createGroupsPupils()
    await createAttendancesPupils()
    await createContracts()
    await createPayrols()
    await createPupilMails()
    await createPupilParents()
}